name: dart_server
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Francisperalta05/DartServer

environment:
  sdk: '>=3.4.4 <4.0.0'

# dart run build_runner build --delete-conflicting-outputs
# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  build_runner: ^2.4.11
  crypto: ^3.0.5
  encrypt: ^5.0.3
  mongo_dart: ^0.10.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0
  shelf_swagger_ui: ^1.0.0+2
  uuid: ^4.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_web_compilers: ^4.0.4
